# base/constants.py
# -*- coding: utf-8 -*-
"""常量定义 - 完整版，包含所有提取器需要的KEYWORDS"""

# 🔥 关键修复：添加完整的KEYWORDS定义
KEYWORDS = {
    "name": ["氏名", "氏 名", "名前", "フリガナ", "Name", "名　前", "姓名"],
    "age": ["年齢", "年龄", "年令", "歳", "才", "Age", "年　齢", "生年月", "満"],
    "gender": ["性別", "性别", "Gender", "性　別"],
    "nationality": ["国籍", "出身国", "出身地", "Nationality", "国　籍"],
    # 🔥 关键修复：experience关键词（arrival_year_extractor依赖）
    "experience": [
        "経験年数",
        "実務経験",
        "開発経験",
        "ソフト関連業務経験年数",
        "IT経験",
        "業務経験",
        "経験",
        "実務年数",
        "Experience",
        "エンジニア経験",
        "経験年月",
        "職歴",
        "IT経験年数",
        "コンピュータソフトウエア関連業務",
        "実務年数",
    ],
    # 🔥 关键修复：arrival关键词（experience_extractor依赖）
    "arrival": [
        "来日",
        "渡日",
        "入国",
        "日本滞在年数",
        "滞在年数",
        "在日年数",
        "来日年",
        "来日時期",
        "来日年月",
        "来日年度",
    ],
    "japanese": [
        "日本語",
        "日語",
        "JLPT",
        "日本語能力",
        "語学力",
        "言語能力",
        "日本語レベル",
        "Japanese",
    ],
    "education": ["学歴", "学校", "大学", "卒業", "専門学校", "高校", "最終学歴"],
    "skills": [
        "技術",
        "スキル",
        "言語",
        "DB",
        "OS",
        "フレームワーク",
        "ツール",
        "Skills",
        "开发语言",
        "プログラミング言語",
        "データベース",
        "開発環境",
        "技術経験",
    ],
}

# 有效的国籍列表
VALID_NATIONALITIES = [
    "中国",
    "日本",
    "韓国",
    "ベトナム",
    "フィリピン",
    "インド",
    "ネパール",
    "アメリカ",
    "ブラジル",
    "台湾",
    "タイ",
    "インドネシア",
    "バングラデシュ",
    "スリランカ",
    "ミャンマー",
    "カンボジア",
    "ラオス",
    "モンゴル",
]

# 技能标记符号
SKILL_MARKS = ["◎", "○", "△", "×", "★", "●", "◯", "▲", "※"]

# 有效技能列表（保持原有定义）
VALID_SKILLS = {
    # 编程语言
    "Java",
    "JAVA",
    "Python",
    "JavaScript",
    "TypeScript",
    "C",
    "C++",
    "C#",
    "C/C++",
    "PHP",
    "Ruby",
    "Go",
    "Kotlin",
    "Swift",
    "Scala",
    "Rust",
    "VB.NET",
    "VB",
    "VBA",
    "COBOL",
    "Perl",
    "R",
    "Objective-C",
    # 前端
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "React",
    "React.js",
    "Vue",
    "Vue.js",
    "Angular",
    "jQuery",
    "Bootstrap",
    "Webpack",
    "Sass",
    "Less",
    # 后端框架
    "Spring",
    "SpringBoot",
    "SpringMVC",
    "Struts",
    "Struts2",
    "Django",
    "Flask",
    "Rails",
    "Express",
    "Node.js",
    ".NET",
    "ASP.NET",
    "Laravel",
    "Thymeleaf",
    "JSF",
    "JSP",
    "Servlet",
    "Java Servlet",
    "Hibernate",
    "MyBatis",
    "Mybatis",
    "JPA",
    # 数据库
    "MySQL",
    "PostgreSQL",
    "Oracle",
    "SQL Server",
    "SQLServer",
    "MongoDB",
    "Redis",
    "DB2",
    "SQLite",
    "Access",
    "Sybase",
    "Azure SQL DB",
    "PL/SQL",
    "Aurora",
    # 工具和平台
    "AWS",
    "Azure",
    "GCP",
    "Docker",
    "Kubernetes",
    "Git",
    "GitHub",
    "GitLab",
    "SVN",
    "TortoiseSVN",
    "SourceTree",
    "Mercurial",
    "Jenkins",
    "GitLab CI",
    "GitHub Actions",
    "CircleCI",
    "Travis CI",
    "Maven",
    "Gradle",
    "Ant",
    "npm",
    "yarn",
    "pip",
    "composer",
    # 开发工具
    "Eclipse",
    "IntelliJ IDEA",
    "Visual Studio",
    "VS Code",
    "Xcode",
    "Android Studio",
    "NetBeans",
    "Sublime Text",
    "Atom",
    "WebStorm",
    "PyCharm",
    "PhpStorm",
    "RubyMine",
    "CLion",
    "DataGrip",
    # 操作系统
    "Windows",
    "Linux",
    "Unix",
    "macOS",
    "Ubuntu",
    "CentOS",
    "Debian",
    "Red Hat",
    "SUSE",
    "AIX",
    "Solaris",
    "FreeBSD",
    # Web服务器
    "Nginx",
    "Apache",
    "IIS",
    "Tomcat",
    "WebLogic",
    "WebSphere",
    "JBoss",
    "Undertow",
    # 消息队列
    "RabbitMQ",
    "Kafka",
    "ActiveMQ",
    "ZeroMQ",
    "Redis Pub/Sub",
    # 其他技术
    "REST",
    "GraphQL",
    "SOAP",
    "gRPC",
    "WebSocket",
    "OAuth",
    "JWT",
    "SSL/TLS",
    "HTTP/HTTPS",
    "TCP/IP",
    "DNS",
    "JSON",
    "XML",
    "YAML",
    "Protobuf",
    # 机器学习/AI
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "OpenCV",
    "NLTK",
    "spaCy",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Jupyter",
    # 大数据
    "Hadoop",
    "Spark",
    "Hive",
    "HBase",
    "Flink",
    "Storm",
    "Zookeeper",
    "Kafka",
    "ElasticSearch",
    "Logstash",
    "Kibana",
    # 移动开发
    "Android",
    "iOS",
    "React Native",
    "Flutter",
    "Xamarin",
    "Ionic",
    "Cordova",
    "Unity",
    "Unreal Engine",
    # 日本特有工具
    "TeraTerm",
    "Tera Term",
    "JP1",
    "Hulft",
    "A5:SQL",
    "秀丸",
    "サクラエディタ",
    "WinSCP",
    "FFFTP",
    "Win95/98",
    "WinNT",
    "Win2000",
    "WinXP",
    "Win7",
    "Win8",
    "Win10",
    "Win11",
}

# 排除模式（用于技能过滤）
EXCLUDE_PATTERNS = [
    r"^\d+$",  # 纯数字
    r"^[A-Z]$",  # 单个大写字母
    r"^(and|or|the|of|in|on|at|to|for)$",  # 常见介词
    r"^(年|月|日|時|分|秒)$",  # 时间单位
    r"^第\d+",  # 第N个
    r"^その他",  # 其他
    r"^備考",  # 备考
    r"^注意",  # 注意
    r"^説明",  # 说明
]

# 工作范围选项
WORK_SCOPE_OPTIONS = [
    "要件定義",
    "基本設計",
    "詳細設計",
    "製造",
    "開発",
    "単体テスト",
    "結合テスト",
    "総合テスト",
    "システムテスト",
    "運用保守",
    "運用",
    "保守",
    "サポート",
    "導入",
    "移行",
    "プロジェクト管理",
    "品質管理",
    "構成管理",
]

# 角色选项
ROLE_OPTIONS = [
    "PM",
    "PL",
    "SL",
    "TL",
    "BSE",
    "SE",
    "PG",
    "PE",
    "アーキテクト",
    "コンサルタント",
    "サポート",
    "QA",
    "QC",
    "テスター",
    "デザイナー",
    "UI/UX",
    "インフラ",
    "DevOps",
    "SRE",
]
